# modules/secrets - Secrets Manager entries for the RDS master password, the
# composed backend DATABASE_URL, and a placeholder for third-party API keys
# (geocoding, map tiles, email/SMS providers, etc.) that get filled in
# out-of-band once real accounts for those services exist.

resource "random_password" "db" {
  length  = 32
  special = false # avoid characters that need extra escaping in connection strings
}

resource "aws_secretsmanager_secret" "db_password" {
  name        = "${var.name_prefix}/db-password"
  description = "Master password for the RDS Postgres instance. Value is generated by Terraform (random_password) on first apply."
}

resource "aws_secretsmanager_secret_version" "db_password" {
  secret_id     = aws_secretsmanager_secret.db_password.id
  secret_string = random_password.db.result
}

# The full DATABASE_URL can't be known until the RDS instance exists (its
# endpoint is only known after the rds module applies), so this starts with a
# placeholder value and `lifecycle.ignore_changes` so Terraform doesn't fight
# with whatever process (deploy pipeline / one-time CLI command) writes the
# real value here after RDS is created.
resource "aws_secretsmanager_secret" "database_url" {
  name        = "${var.name_prefix}/database-url"
  description = "Full SQLAlchemy DATABASE_URL consumed by the backend ECS tasks (api + worker)."
}

resource "aws_secretsmanager_secret_version" "database_url" {
  secret_id     = aws_secretsmanager_secret.database_url.id
  secret_string = "postgresql+psycopg://REPLACE_ME:REPLACE_ME@REPLACE_ME:5432/REPLACE_ME"

  lifecycle {
    ignore_changes = [secret_string]
  }
}

# Placeholder container for third-party API keys. Fill in real values
# out-of-band (AWS console or `aws secretsmanager put-secret-value`) once
# those accounts/plans exist - never commit real keys to git.
resource "aws_secretsmanager_secret" "third_party_api_keys" {
  name        = "${var.name_prefix}/third-party-api-keys"
  description = "JSON blob of third-party API keys: production map tiles, email/SMS alert provider, paid geocoding/enrichment providers, etc. See infra/BLOCKERS.md."
}

resource "aws_secretsmanager_secret_version" "third_party_api_keys" {
  secret_id     = aws_secretsmanager_secret.third_party_api_keys.id
  secret_string = jsonencode({})

  lifecycle {
    ignore_changes = [secret_string]
  }
}
