"""initial schema

Revision ID: e359ecd74fb9
Revises: 
Create Date: 2026-07-25 20:51:40.578965

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e359ecd74fb9'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('jurisdictions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('state', sa.String(length=2), nullable=False),
    sa.Column('level', sa.String(length=32), nullable=False),
    sa.Column('timezone', sa.String(length=64), nullable=False),
    sa.Column('source_system', sa.Enum('SOCRATA', 'ARCGIS', 'MANUAL', name='sourcesystem', native_enum=False, length=32), nullable=False),
    sa.Column('source_config', sa.JSON(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', 'state', name='uq_jurisdiction_name_state')
    )
    op.create_table('organizations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('properties',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('address', sa.String(length=500), nullable=False),
    sa.Column('normalized_address', sa.String(length=500), nullable=True),
    sa.Column('city', sa.String(length=255), nullable=True),
    sa.Column('state', sa.String(length=2), nullable=True),
    sa.Column('zip_code', sa.String(length=10), nullable=True),
    sa.Column('parcel_number', sa.String(length=128), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('geocode_source', sa.String(length=64), nullable=True),
    sa.Column('geocode_confidence', sa.Float(), nullable=True),
    sa.Column('property_type', sa.String(length=128), nullable=True),
    sa.Column('year_built', sa.Integer(), nullable=True),
    sa.Column('lot_size_sqft', sa.Float(), nullable=True),
    sa.Column('building_size_sqft', sa.Float(), nullable=True),
    sa.Column('bedrooms', sa.Float(), nullable=True),
    sa.Column('bathrooms', sa.Float(), nullable=True),
    sa.Column('stories', sa.Float(), nullable=True),
    sa.Column('enrichment', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('properties', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_properties_normalized_address'), ['normalized_address'], unique=False)
        batch_op.create_index(batch_op.f('ix_properties_parcel_number'), ['parcel_number'], unique=False)

    op.create_table('api_keys',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('key_prefix', sa.String(length=16), nullable=False),
    sa.Column('key_hash', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key_hash')
    )
    op.create_table('owners',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('property_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('owner_type', sa.String(length=64), nullable=True),
    sa.Column('mailing_address', sa.String(length=500), nullable=True),
    sa.Column('is_owner_occupied', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('permits',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('jurisdiction_id', sa.Integer(), nullable=False),
    sa.Column('property_id', sa.Integer(), nullable=True),
    sa.Column('permit_number', sa.String(length=128), nullable=False),
    sa.Column('permit_type', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=128), nullable=True),
    sa.Column('application_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('issue_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completion_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expiration_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('contractor', sa.String(length=255), nullable=True),
    sa.Column('builder', sa.String(length=255), nullable=True),
    sa.Column('architect', sa.String(length=255), nullable=True),
    sa.Column('engineer', sa.String(length=255), nullable=True),
    sa.Column('property_address', sa.String(length=500), nullable=True),
    sa.Column('parcel_number', sa.String(length=128), nullable=True),
    sa.Column('estimated_cost', sa.Float(), nullable=True),
    sa.Column('valuation', sa.Float(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('work_category', sa.String(length=128), nullable=True),
    sa.Column('square_footage', sa.Float(), nullable=True),
    sa.Column('units', sa.Integer(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('permit_url', sa.String(length=1000), nullable=True),
    sa.Column('source', sa.String(length=128), nullable=True),
    sa.Column('raw_data', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['jurisdiction_id'], ['jurisdictions.id'], ),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('jurisdiction_id', 'permit_number', name='uq_permit_jurisdiction_number')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('permit_versions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('permit_id', sa.Integer(), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('snapshot', sa.JSON(), nullable=False),
    sa.Column('changed_fields', sa.JSON(), nullable=False),
    sa.Column('recorded_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['permit_id'], ['permits.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('permit_id', 'version_number', name='uq_permit_version_number')
    )
    op.create_table('scores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('permit_id', sa.Integer(), nullable=False),
    sa.Column('project_size_score', sa.Float(), nullable=False),
    sa.Column('project_size_explanation', sa.Text(), nullable=False),
    sa.Column('budget_tier', sa.String(length=32), nullable=False),
    sa.Column('budget_tier_explanation', sa.Text(), nullable=False),
    sa.Column('urgency_score', sa.Float(), nullable=False),
    sa.Column('urgency_explanation', sa.Text(), nullable=False),
    sa.Column('luxury_likelihood', sa.Float(), nullable=False),
    sa.Column('luxury_explanation', sa.Text(), nullable=False),
    sa.Column('remodel_vs_repair', sa.String(length=32), nullable=False),
    sa.Column('remodel_vs_repair_explanation', sa.Text(), nullable=False),
    sa.Column('investment_property_likelihood', sa.Float(), nullable=False),
    sa.Column('investment_property_explanation', sa.Text(), nullable=False),
    sa.Column('lead_score', sa.Float(), nullable=False),
    sa.Column('lead_score_explanation', sa.Text(), nullable=False),
    sa.Column('confidence_score', sa.Float(), nullable=False),
    sa.Column('confidence_explanation', sa.Text(), nullable=False),
    sa.Column('computed_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['permit_id'], ['permits.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('scores')
    op.drop_table('permit_versions')
    op.drop_table('users')
    op.drop_table('permits')
    op.drop_table('owners')
    op.drop_table('api_keys')
    with op.batch_alter_table('properties', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_properties_parcel_number'))
        batch_op.drop_index(batch_op.f('ix_properties_normalized_address'))

    op.drop_table('properties')
    op.drop_table('organizations')
    op.drop_table('jurisdictions')
    # ### end Alembic commands ###
