variable "aws_region" {
  description = "AWS region to deploy into."
  type        = string
  default     = "us-east-1"
}

variable "project_name" {
  description = "Short project name used as a prefix for resource names and tags."
  type        = string
  default     = "construction-intel"
}

variable "environment" {
  description = "Deployment environment name (e.g. prod, staging)."
  type        = string
  default     = "prod"
}

variable "vpc_cidr" {
  description = "CIDR block for the VPC."
  type        = string
  default     = "10.20.0.0/16"
}

variable "az_count" {
  description = "Number of availability zones to spread public/private subnets across."
  type        = number
  default     = 2
}

variable "db_name" {
  description = "Name of the application database created on the RDS instance."
  type        = string
  default     = "construction_intel"
}

variable "db_username" {
  description = "Master username for RDS. The master password is generated by Terraform (random_password) and stored in Secrets Manager - it is never passed as a plain variable."
  type        = string
  default     = "construction_intel_admin"
}

variable "db_instance_class" {
  description = "RDS instance class. db.t4g.micro is Free-Tier eligible for the first 12 months of a NEW AWS account (750 hrs/month); after that or on an existing account it is billed normally."
  type        = string
  default     = "db.t4g.micro"
}

variable "db_allocated_storage_gb" {
  description = "Initial RDS storage in GB (gp3). 20 GB is the Free-Tier allowance for a new account."
  type        = number
  default     = 20
}

variable "redis_node_type" {
  description = "ElastiCache node type. cache.t4g.micro is the cheapest current-generation node; check current Free-Tier terms before relying on it being free."
  type        = string
  default     = "cache.t4g.micro"
}

variable "api_image_tag" {
  description = "Docker image tag (in ECR) to deploy for the FastAPI backend service."
  type        = string
  default     = "latest"
}

variable "worker_image_tag" {
  description = "Docker image tag (in ECR) to deploy for the Celery worker service."
  type        = string
  default     = "latest"
}

variable "api_cpu" {
  description = "Fargate task CPU units for the API service (256 = .25 vCPU)."
  type        = number
  default     = 512
}

variable "api_memory" {
  description = "Fargate task memory (MB) for the API service."
  type        = number
  default     = 1024
}

variable "api_desired_count" {
  description = "Number of API tasks to run. Keep at 1 for early-stage/low-traffic to minimize cost."
  type        = number
  default     = 1
}

variable "worker_cpu" {
  description = "Fargate task CPU units for the Celery worker service."
  type        = number
  default     = 512
}

variable "worker_memory" {
  description = "Fargate task memory (MB) for the Celery worker service."
  type        = number
  default     = 1024
}

variable "worker_desired_count" {
  description = "Number of Celery worker tasks to run."
  type        = number
  default     = 1
}

variable "alarm_notification_email" {
  description = "Email address subscribed to the CloudWatch/SNS alarm topic. Leave empty (default) to skip creating the subscription - AWS emails a confirmation link the first time a real address is set, so this is intentionally not auto-populated."
  type        = string
  default     = ""
}

variable "tags" {
  description = "Additional common tags merged onto every resource's default tags."
  type        = map(string)
  default     = {}
}
